name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'
          distribution: 'temurin' # 'adopt' is now 'temurin'

      - name: Build the package
        run: mvn --batch-mode -DskipTests package

      - name: Run the unit tests
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Publish test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.ACCESS_TOKEN}} | docker login ghcr.io --username prithvia28 --password-stdin

      - name: Build and push the image
        run: |
          docker build -t ghcr.io/prithvia28/primes-service:latest --file Dockerfile .
          docker push ghcr.io/prithvia28/primes-service:latest
